context:
  version: "0.82"

package:
  name: jimtcl
  version: "{{ version }}"

source:
  - git_url: https://github.com/msteveb/jimtcl.git
    git_rev: "{{ version }}"
  - sel(win):
      path: build.sh

build:
  number: 0

requirements:
  build:
  - sel(not win):
    - "{{ compiler('c') }}"
    - make
    - pkg-config
  - sel(win):
    - m2w64-gcc
    - m2w64-make
    - m2-bash
    - m2-coreutils
    - m2-sed
    - m2-pkg-config
  host:
  - sel(not win):
    - zlib
    - openssl
  - sel(win):
    - m2w64-zlib
  run:
    - sel(win):
      - m2w64-zlib

test:
  commands:
  - jimsh --version
